### PR TITLE
Force set device performance class to high and etc.

### PR DESCRIPTION
**Pull request by soranerai**
thats unlock some features (at least blur mode in navbar)

### CODE REVIEW

**Comment by aire1** [comment]
account limit count in one app is still 4, need to watch more to break this

**Comment by shatyuka** [comment]
Does `hasPremiumOnAccounts` work?

**Comment by aire1** [comment]
Telegram uses this method to check if at least one account has premium. It doesn't unlock stickers or anything like that, but it does let you choose a premium icon in the settings.

**Comment by aire1** [comment]
More about account limit.
`org.telegram.messenger.UserConfig` contains static values `MAX_ACCOUNT_COUNT` and `MAX_ACCOUNT_DEFAULT_COUNT`
According on [this](https://github.com/DrKLO/Telegram/blob/96dce2c9aabc33b87db61d830aa087b6b03fe397/TMessagesProj/src/main/java/org/telegram/ui/LaunchActivity.java#L550-L572) code fragment, if we change them to some larger value it should works, **but it does't**. idk why

**Comment by ayanamist** [comment]
> More about account limit. `org.telegram.messenger.UserConfig` contains static values `MAX_ACCOUNT_COUNT` and `MAX_ACCOUNT_DEFAULT_COUNT` According on [this](https://github.com/DrKLO/Telegram/blob/96dce2c9aabc33b87db61d830aa087b6b03fe397/TMessagesProj/src/main/java/org/telegram/ui/LaunchActivity.java#L550-L572) code fragment, if we change them to some larger value it should works, **but it does't** if i replace them with `setStaticObjectField`. idk why. maybe you can handle it :Р

Because the static final fields will be inlined by compiler during compiling.

**Pull request merged**
